server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abuhurairaa/Hotel-Microservices-Config
          clone-on-start: true
